### ISSUE TITLE
Wrong data from scale

### ISSUE THREAD

**Issue by PaloSP** [lswiderski/mi-scale-exporter#9] opened 2022-09-18 08:13 UTC
Hello and thank you for your work!

I am trying to use this app with my scale Mi Body Composition Scale 2 (XMTZC05HM) and Redmi Note 11 Pro 5G with Android 11. But I am getting wrong (not some as in my Zepp Life) data. I am using 1.7 release.. new alpha version was crashing before I get any data from scale. Is there any way how can I figure out what's going on without installing Xamarin and other stuff to debug it on my side? 

In Zepp Life:
Weight: 67,95
BMI: 22,1
Body Fat: 17,7
Muscle Mass: 53,11
Water: 56,5
Bone mass: 2,85
Visceral fat: 8
Body age: 23
Protein: 21,7
Basal: 1477

In your app:
Weight: 67,95
BMI: 22,4
Body Fat: 18,1
Muscle Mass: 52,81
Water: 56,2
Bone mass: 2,83
Visceral fat: 9
Body age: 24
Protein: 21,5
Basal: 1478

![1663489135855](https://user-images.githubusercontent.com/32291845/190892808-4fb78f8c-41f5-4952-af2c-132a18789f80.jpg)

**Comment by lswiderski** [comment] 2022-09-20 06:36
Hi @PaloSP and thank you for your feedback.
As to the correctness of the data, We do not know how exactly Xiaomi calculate a body composition from this raw data, everything is based on reverse engineering and conjecture. As a result, there may be slightly different results than in the Zepp life application (e.g. in my personal case it is a different body type).

But BMI calculation is simple should be exactly the same in both apps. Are you sure You have provided the same height as in Zepp life?

About the alpha version, it crash on start, or when you start measurement or in different moment? Can you check manually app permissions?

**Comment by michalbielecki** [comment] 2022-09-20 07:42
I can confirm that alpha version (maui branch) works fine only on the fresh first run (clear all app data, assign location, devices nearby accesses). For some reason, if i'll try to get the data next day, interface will freeze after clicking scan. After such freeze, if app is stopped, data cleared and permissions reassigned it will be able to get the data from the scale and upload it to the cloud. (I'm using Mi Body Composition Scale 2 if that matters).

**Comment by lswiderski** [comment] 2022-09-20 07:45
@michalbielecki Thanks for report. I know there is problem with password field, when it's prefilled then the view freeze. When password is not saved then it works fine.

**Comment by lswiderski** [comment] 2022-11-07 19:14
The newest beta version is free from this crashing bug and because we found a reason of incorrect data, I will close this issue.
https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.0.0-beta

**Closed by lswiderski** 2022-11-07 19:14 UTC
